-- Seed: HandySam product catalog (Trinity Petroleum quote, Sep 2026)
insert into handysam_products (venture, category, description, uom, cost, sell, stock, flagged) values
('handysam', 'MGPS', '12mm Degreased Copper Pipe', 'Mtr', 1100, 1100, 0, false),
('handysam', 'MGPS', '15mm Degreased Copper Pipe', 'Mtr', 1300, 1300, 0, false),
('handysam', 'MGPS', '22mm Degreased Copper Pipe', 'Mtr', 2100, 2100, 0, false),
('handysam', 'MGPS', '28mm Degreased Copper Pipe', 'Mtr', null, null, 0, true),
('handysam', 'MGPS', '12mm Degreased Copper Elbow', 'Pcs', 130, 130, 0, false),
('handysam', 'MGPS', '15mm Degreased Copper Elbow', 'Pcs', 180, 180, 0, false),
('handysam', 'MGPS', '22mm Degreased Copper Elbow', 'Pcs', 250, 250, 0, false),
('handysam', 'MGPS', '28mm Degreased Copper Elbow', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '12mm Degreased Copper Tee', 'Pcs', 170, 170, 0, false),
('handysam', 'MGPS', '15mm Degreased Copper Tee', 'Pcs', 250, 250, 0, false),
('handysam', 'MGPS', '22mm Degreased Copper Tee', 'Pcs', 450, 450, 0, false),
('handysam', 'MGPS', '28mm Degreased Copper Tee', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '12mm Degreased Copper Coupler', 'Pcs', 100, 100, 0, false),
('handysam', 'MGPS', '15mm Degreased Copper Coupler', 'Pcs', 150, 150, 0, false),
('handysam', 'MGPS', '22mm Degreased Copper Coupler', 'Pcs', 200, 200, 0, false),
('handysam', 'MGPS', '28mm Degreased Copper Coupler', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '12mm Degreased Copper Coupler', 'Pcs', 100, 100, 0, false),
('handysam', 'MGPS', '15*12mm Degreased Reducer', 'Pcs', 150, 150, 0, false),
('handysam', 'MGPS', '22*15mm Degreased Reducer', 'Pcs', 200, 200, 0, false),
('handysam', 'MGPS', 'Oxygen Outlets', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', 'N2O Outlets', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', 'MA4 Outlets', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', 'Vacuum Outlets', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', 'AGSS Outlet (active)', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', 'AGSS Outlet (air driven)', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '15mm Line Valve', 'Pcs', 12000, 12000, 0, false),
('handysam', 'MGPS', '22mm Line valve', 'Pcs', 15000, 15000, 0, false),
('handysam', 'MGPS', '3 Gas AVSU', 'Pcs', 55000, 55000, 0, false),
('handysam', 'MGPS', '5 Gas AVSU', 'Pcs', 90000, 90000, 0, false),
('handysam', 'MGPS', 'ZVSU', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '2*2 Manifold Banks', 'Unit', null, null, 0, true),
('handysam', 'MGPS', '3*2 Manifold Banks', 'Unit', null, null, 0, true),
('handysam', 'MGPS', '4*2 Manifold Banks', 'Unit', 249000, 249000, 0, false),
('handysam', 'MGPS', '5*2 Manifold Banks', 'Unit', null, null, 0, true),
('handysam', 'MGPS', '6*2 Manifold Banks', 'Unit', 341000, 341000, 0, false),
('handysam', 'MGPS', '8*2 Manifold Banks', 'Unit', null, null, 0, true),
('handysam', 'MGPS', '10*2 Manifold Banks', 'Unit', null, null, 0, true),
('handysam', 'MGPS', 'Automatic Changeover', 'Unit', null, null, 0, true),
('handysam', 'MGPS', 'Semi Automatic Changeover', 'Unit', null, null, 0, true),
('handysam', 'MGPS', '1 Gas Alarm Panel', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '3 Gas Alarm Panel', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '5 Gas Alarm Panel', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', 'Bed Head Unit 1 gas', 'Unit', null, null, 0, true),
('handysam', 'MGPS', 'Bed Head Unit 2 Gas', 'Unit', null, null, 0, true),
('handysam', 'MGPS', 'Bed Head Unit 3 Gas', 'Unit', null, null, 0, true),
('handysam', 'MGPS', 'Bed Head Unit 4 Gas', 'Unit', null, null, 0, true),
('handysam', 'MGPS', '15mm Munsen Rings', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '22mm Munsen Rings', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '28mm Munsen Rings', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '12mm Plastic Clips', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '15mm Plastic Clips', 'Pcs', null, null, 0, true),
('handysam', 'MGPS', '22mm Plastic Clips', 'Pcs', null, null, 0, true),
('handysam', 'Delivery Devices', '2 stage Oxygen Regulator', 'Pcs', null, null, 0, true),
('handysam', 'Delivery Devices', 'Single Oxygen Flowmeter', 'Pcs', null, null, 0, true),
('handysam', 'Delivery Devices', 'Single Stage Regulator', 'Pcs', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'Flexible Pigtails', 'Pcs', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'Oxygen Bullnose', 'Pcs', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'N20 Bullnose', 'Pcs', null, null, 0, true),
('handysam', 'Spare Parts & Kits', '22mm NRV', 'Pcs', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'Oxygen Braided PressureHose (white)', 'Mtr', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'MA4 Braided Pressure Hose (Black and white)', 'Mtr', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'Vacuum Braided Pressure Hose (Yellow)', 'Mtr', null, null, 0, true),
('handysam', 'Spare Parts & Kits', 'N20 Braided Pressure Hose (Blue)', 'Mtr', null, null, 0, true),
('handysam', 'Hospital Doors', 'Single Leaf Swing Door Standard', 'Pcs', null, null, 0, true),
('handysam', 'Hospital Doors', 'Double Leaf Swing Door Standard', 'Pcs', null, null, 0, true),
('handysam', 'Hospital Doors', 'Sliding Door Standard', 'Pcs', null, null, 0, true),
('handysam', 'Nurse Call Systems Wireless', 'Bedside Call Unit', 'Pcs', null, null, 0, true),
('handysam', 'Nurse Call Systems Wireless', 'Overdoor lamp', 'Pcs', null, null, 0, true),
('handysam', 'Nurse Call Systems Wireless', 'Display Unit', 'Pcs', null, null, 0, true),
('handysam', 'Nurse Call Systems Wireless', 'Pull Cord', 'Pcs', null, null, 0, true),
('handysam', 'Nurse Call Systems Wireless', 'Repeater', 'Pcs', null, null, 0, true);
